name: My Workflow

on: workflow_dispatch

jobs:

  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Something I doubt your commitment to sparkle motion"
      
      - name: Step 2
        run: echo "Why do you wear that stupid bunny suit?"
        
