name: My Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Sometimes I doubt your commitment to Sparkle Motion"
      
      - name: Step 2
        run: echo "Why do you wear that stupid bunny suit?"
        
      - name: Take your Time
        run: sleep 30
        
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Cellar door"
    
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: green
          SLACK_MESSAGE: 'Test :rocket:'
          SLACK_WEBHOOK: https://hooks.slack.com/services/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

