name: Build & Test

on: 
  push:
    branches:
      - main

jobs:
  
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout branch
        uses: actions/checkout@v3
    
      - name: Installing Package Dependencies
        run: yarn install

      - name: Build Application
        run: yarn build
        

  notify:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
